### ISSUE TITLE
What exactly have you done with MergeKit?

### ISSUE THREAD

**Issue by sunshicheng1** [allenai/open-instruct#463]
Hello, I would like to ask about the specific operations regarding model fusion mentioned in the paper. The paper only contains a few sentences, and I didn't understand them. Could you please help?

**Comment by vwxyzjn** [comment]
@jacob-morrison has those details, but he is busy at the moment. Please check back in ~ a month.

**Comment by AllenShow** [comment]
Also want to know the details. Thanks.

**Comment by jacob-morrison** [comment]
Hi! We used MergeKit: https://github.com/arcee-ai/mergekit to merge our models together. We used linear weighted merging, and here's an example mergekit config.yaml:

```
models:
  - model: model-one-directory/
    parameters:
      weight: 1.0
  - model: model-two-directory/
    parameters:
      weight: 1.0
  - model: model-three-directory/
    parameters:
      weight: 1.0
normalize: true
merge_method: linear
dtype: bfloat16
```

Using a config like this, run with a command like the one in the mergekit repo (e.g. `mergekit-yaml path/to/your/config.yml ./output-model-directory [--cuda]`), this will create a model soup of the three models the config refers to.
